import * as THREE from 'three';
import { Rng } from '../../util/Rng.js';
import { PartBuilder } from './PartBuilder.js';
import {
  concreteMaterial, paintedMaterial, rustMaterial, woodMaterial,
  glowMaterial, markerTexture,
} from './PropMaterials.js';
import { alphaTex } from '../veg/VegTextures.js';

/**
 * Everything a real highway carries and an empty landscape does not: crash
 * barrier on the outside of the bends, delineator posts marching to the
 * horizon, distance markers, culvert headwalls where the road crosses a wash,
 * a gravel shoulder, litter, skid marks and a couple of dead cars.
 *
 * All of it is generated by walking the road spline in arc length, so the
 * spacing is even whether the route is running north or east, and merged per
 * material — the whole set is under ten draw calls.
 */

const _m = new THREE.Matrix4();
const _e = new THREE.Euler();
const _q = new THREE.Quaternion();

function mat4(pos, rot = [0, 0, 0], scale = [1, 1, 1]) {
  _e.set(rot[0], rot[1], rot[2]);
  _q.setFromEuler(_e);
  return new THREE.Matrix4().compose(
    new THREE.Vector3(pos[0], pos[1], pos[2]), _q,
    new THREE.Vector3(scale[0], scale[1], scale[2])
  );
}

/** Twin dark tyre streaks for skid-mark decals. */
function skidTexture() {
  return alphaTex(128, (ctx, s) => {
    ctx.fillStyle = '#000000';
    for (const cx of [s * 0.33, s * 0.67]) {
      const g = ctx.createLinearGradient(0, 0, 0, s);
      g.addColorStop(0, 'rgba(0,0,0,0)');
      g.addColorStop(0.25, 'rgba(0,0,0,0.75)');
      g.addColorStop(0.8, 'rgba(0,0,0,0.5)');
      g.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.fillStyle = g;
      ctx.fillRect(cx - s * 0.07, 0, s * 0.14, s);
    }
  }, { alphaRef: 0.02 });
}

export class RoadFurniture {
  /**
   * @param {import('../veg/Ecology.js').Ecology} eco
   * @param {THREE.Scene} scene
   */
  constructor(eco, scene) {
    this.eco = eco;
    this.scene = scene;
    this.root = new THREE.Group();
    this.root.name = 'road_furniture';
  }

  build() {
    const M = this.mats = {
      concrete: concreteMaterial(0x9d9689, 0.93),
      guard: paintedMaterial(0xa9aeb2, 0.46, 0.72),
      post: paintedMaterial(0xd7d2c4, 0.62, 0.15),
      rust: rustMaterial(0x8a5a38, 0.5),
      wood: woodMaterial(0x6f5c44),
      dark: new THREE.MeshStandardMaterial({ color: 0x25262a, roughness: 0.78, metalness: 0.25 }),
      reflect: glowMaterial(0xffb54a, 0.6, 0x2a1a08),
      plate: new THREE.MeshStandardMaterial({
        map: markerTexture(0), roughness: 0.6, metalness: 0.05, side: THREE.DoubleSide,
      }),
      chevron: new THREE.MeshStandardMaterial({
        map: markerTexture(1), roughness: 0.6, metalness: 0.05, side: THREE.DoubleSide,
      }),
    };
    for (const k of Object.keys(M)) M[k].name = `road_${k}`;

    this.samples = this.eco.roadSamples({ step: 6, radius: 780 });

    // Bucket the furniture into 150 m chunks of road. Merging the whole
    // kilometre into one mesh would give it a kilometre-wide bounding sphere,
    // which the frustum can never reject and every shadow cascade would then
    // redraw; per-chunk groups cost a few more objects and far fewer calls.
    this._chunks = new Map();
    const B = this._chunkFor.bind(this);
    this._delineators(B);
    this._guardrail(B);
    this._markers(B);
    this._culverts(B);
    this._litter(B);
    this.chunkGroups = [];
    for (const [key, builder] of this._chunks) {
      const g = new THREE.Group();
      const cast = key.endsWith(':c');
      g.name = `roadchunk_${key}`;
      builder.build(g, { cast, receive: true, name: 'roadkit' });
      const c = new THREE.Vector3();
      let n = 0;
      for (const m of g.children) {
        if (!m.geometry.boundingSphere) m.geometry.computeBoundingSphere();
        c.add(m.geometry.boundingSphere.center); n++;
      }
      if (n) c.divideScalar(n);
      this.root.add(g);
      this.chunkGroups.push({ group: g, center: c, canCast: cast });
    }
    this._chunks = null;

    this._shoulderGravel();
    this._skidMarks();
    this.scene.add(this.root);
  }

  /**
   * The PartBuilder owning the 150 m of road that `s` falls in.
   *
   * Two builders per chunk: things whose shadow is load-bearing (posts, rail)
   * and things whose shadow nobody would ever notice (litter, gravel aprons,
   * sign faces). Only the first set is ever handed to the cascades, which is
   * worth three draw calls per material it saves.
   */
  _chunkFor(s, cast = false) {
    const key = `${Math.floor((s || 0) / 150)}:${cast ? 'c' : 'n'}`;
    let b = this._chunks.get(key);
    if (!b) { b = new PartBuilder(); this._chunks.set(key, b); }
    return b;
  }

  /** Perpendicular offset from a road sample. */
  _side(p, off) {
    return { x: p.x + p.tz * off, z: p.z - p.tx * off };
  }

  // ------------------------------------------------------------ delineators

  /**
   * White marker posts on both verges every 24 m. Nothing sells "highway"
   * faster than a line of identical objects converging to a vanishing point.
   */
  _delineators(bucket) {
    const M = this.mats, eco = this.eco;
    const rng = new Rng(8080);
    const shaft = new THREE.BoxGeometry(0.13, 1.25, 0.08);
    const head = new THREE.BoxGeometry(0.12, 0.2, 0.065);
    let acc = 1e9;
    for (const p of this.samples) {
      acc += 6;
      if (acc < 24) continue;
      acc = 0;
      const B = bucket(p.s, true);
      const G = bucket(p.s, false);
      for (const side of [-1, 1]) {
        if (rng.next() < 0.06) continue;             // a few knocked flat
        const q = this._side(p, side * 6.6);
        const y = eco.height(q.x, q.z);
        const yaw = Math.atan2(p.tx, p.tz);
        const lean = rng.gauss(0, 0.05);
        B.add(M.post, shaft, mat4([q.x, y + 0.6, q.z], [lean, yaw, rng.gauss(0, 0.06)]));
        G.add(M.reflect, head, mat4([q.x, y + 1.06, q.z], [lean, yaw, 0]));
      }
    }
  }

  // -------------------------------------------------------------- guardrail

  /**
   * W-beam barrier on the stretches where the ground falls away from the
   * shoulder — which is where a real highway authority would have paid for it.
   */
  _guardrail(bucket) {
    const M = this.mats, eco = this.eco;
    const rng = new Rng(2121);
    const posts = new THREE.BoxGeometry(0.14, 1.05, 0.14);
    let run = [];
    const flush = () => {
      if (run.length > 4) {
        for (let i = 0; i < run.length - 1; i++) {
          const a = run[i], b = run[i + 1];
          const B = bucket(a.s, true);
          const len = Math.hypot(b.x - a.x, b.z - a.z);
          const yaw = Math.atan2(b.x - a.x, b.z - a.z);
          const my = (a.y + b.y) * 0.5 + 0.62;
          const mx = (a.x + b.x) * 0.5, mz = (a.z + b.z) * 0.5;
          // three thin ribs make a passable W profile at any distance we see it
          for (const [dy, dz, h] of [[0.11, 0.0, 0.13], [0.0, 0.045, 0.1], [-0.11, 0.0, 0.13]]) {
            B.add(M.guard, new THREE.BoxGeometry(len + 0.1, h, 0.05),
              mat4([mx, my + dy, mz], [0, yaw + Math.PI / 2, 0])
                .multiply(new THREE.Matrix4().makeTranslation(0, 0, dz)));
          }
          if (i % 2 === 0) {
            B.add(M.dark, posts, mat4([a.x, a.y + 0.42, a.z], [0, yaw, rng.gauss(0, 0.03)]));
          }
        }
      }
      run = [];
    };

    for (const p of this.samples) {
      // does the shoulder fall away on the outside of this bend?
      let best = null;
      for (const side of [-1, 1]) {
        const near = this._side(p, side * 7.5);
        const far = this._side(p, side * 17);
        const drop = eco.height(near.x, near.z) - eco.height(far.x, far.z);
        if (drop > 2.6 && (!best || drop > best.drop)) {
          best = { drop, q: this._side(p, side * 7.2) };
        }
      }
      if (!best) { flush(); continue; }
      const y = eco.height(best.q.x, best.q.z);
      run.push({ x: best.q.x, z: best.q.z, y, s: p.s });
      if (run.length > 26) flush();
    }
    flush();
  }

  // ---------------------------------------------------------------- markers

  /** Distance plates every 200 m and hazard chevrons on the sharpest bends. */
  _markers(bucket) {
    const M = this.mats, eco = this.eco;
    let acc = 1e9;
    for (let i = 2; i < this.samples.length - 2; i++) {
      const p = this.samples[i];
      acc += 6;
      const a = this.samples[i - 2], b = this.samples[i + 2];
      const turn = Math.abs(a.tx * b.tz - a.tz * b.tx);
      const yaw = Math.atan2(p.tx, p.tz);
      const B = bucket(p.s);

      if (turn > 0.30 && acc > 60) {
        acc = 0;
        // chevron board on the outside of the corner
        const side = (a.tx * b.tz - a.tz * b.tx) > 0 ? 1 : -1;
        const q = this._side(p, side * 9.5);
        const y = eco.height(q.x, q.z);
        B.add(M.dark, new THREE.CylinderGeometry(0.05, 0.06, 1.9, 6), mat4([q.x, y + 0.9, q.z]));
        B.add(M.chevron, new THREE.PlaneGeometry(1.5, 0.62), mat4([q.x, y + 1.55, q.z], [0, yaw + Math.PI / 2, 0]));
      } else if (acc > 200) {
        acc = 0;
        const q = this._side(p, -8.2);
        const y = eco.height(q.x, q.z);
        B.add(M.concrete, new THREE.BoxGeometry(0.26, 1.15, 0.18), mat4([q.x, y + 0.5, q.z], [0, yaw, 0]));
        B.add(M.plate, new THREE.PlaneGeometry(0.24, 0.3), mat4([q.x, y + 0.86, q.z], [0, yaw + Math.PI / 2, 0])
          .multiply(new THREE.Matrix4().makeTranslation(0, 0, 0.1)));
      }
    }
  }

  // ---------------------------------------------------------------- culverts

  /** Concrete headwalls and a pipe mouth wherever the road crosses a wash. */
  _culverts(bucket) {
    const M = this.mats, eco = this.eco;
    let acc = 1e9, placed = 0;
    for (const p of this.samples) {
      acc += 6;
      if (acc < 90 || placed > 6) continue;
      const up = this._side(p, 16), down = this._side(p, -16);
      const dh = eco.height(up.x, up.z) - eco.height(down.x, down.z);
      if (Math.abs(dh) < 5) continue;
      acc = 0; placed++;
      const B = bucket(p.s);
      const side = dh > 0 ? -1 : 1;
      const q = this._side(p, side * 8.4);
      const y = eco.height(q.x, q.z);
      const yaw = Math.atan2(p.tx, p.tz);
      // headwall with wing walls
      B.add(M.concrete, new THREE.BoxGeometry(3.4, 1.9, 0.4), mat4([q.x, y + 0.5, q.z], [0, yaw + Math.PI / 2, 0]));
      for (const s of [-1, 1]) {
        B.add(M.concrete, new THREE.BoxGeometry(1.5, 1.4, 0.3),
          mat4([q.x + p.tx * s * 1.6, y + 0.4, q.z + p.tz * s * 1.6], [0, yaw + Math.PI / 2 + s * 0.5, 0]));
      }
      const pipe = new THREE.CylinderGeometry(0.62, 0.62, 1.2, 12, 1, true);
      pipe.rotateZ(Math.PI / 2);
      B.add(M.concrete, pipe, mat4([q.x + p.tz * side * 0.4, y + 0.42, q.z - p.tx * side * 0.4], [0, yaw + Math.PI / 2, 0]));
      // scour apron of loose stone below the outfall
      for (let k = 0; k < 7; k++) {
        const r = 1.2 + k * 0.55;
        const px = q.x + p.tz * side * r, pz = q.z - p.tx * side * r;
        B.add(M.concrete, new THREE.BoxGeometry(0.5, 0.22, 0.4),
          mat4([px, eco.height(px, pz) + 0.06, pz], [0, k * 1.7, 0]));
      }
    }
  }

  // ------------------------------------------------------------------ litter

  /** Oil drums, a shredded tyre, crates: the things that fall off trucks. */
  _litter(bucket) {
    const M = this.mats, eco = this.eco;
    const rng = new Rng(6161);
    const drum = new THREE.CylinderGeometry(0.3, 0.3, 0.88, 12);
    const tyre = new THREE.TorusGeometry(0.42, 0.16, 6, 12);
    const crate = new THREE.BoxGeometry(0.72, 0.5, 0.6);
    let acc = 1e9;
    for (const p of this.samples) {
      acc += 6;
      if (acc < 55) continue;
      acc = 0;
      const B = bucket(p.s);
      const n = rng.next() < 0.55 ? 1 : 3;
      for (let i = 0; i < n; i++) {
        const off = rng.sign() * rng.range(7, 14);
        const q = this._side(p, off);
        const px = q.x + rng.gauss(0, 1.6), pz = q.z + rng.gauss(0, 1.6);
        const y = eco.height(px, pz);
        const r = rng.next();
        if (r < 0.42) {
          const fell = rng.next() < 0.45;
          B.add(M.rust, drum, mat4([px, y + (fell ? 0.3 : 0.44), pz],
            fell ? [Math.PI / 2, rng.next() * 3, rng.gauss(0, 0.2)] : [rng.gauss(0, 0.06), rng.next() * 3, 0]));
        } else if (r < 0.72) {
          B.add(M.dark, tyre, mat4([px, y + 0.15, pz], [Math.PI / 2 + rng.gauss(0, 0.25), rng.next() * 3, 0]));
        } else {
          B.add(M.wood, crate, mat4([px, y + 0.24, pz], [rng.gauss(0, 0.1), rng.next() * 3, rng.gauss(0, 0.1)]));
        }
      }
    }
  }

  // ----------------------------------------------------------- shoulder grit

  /** A band of loose stone either side of the carriageway, instanced. */
  _shoulderGravel() {
    const eco = this.eco;
    const rng = new Rng(9393);
    const geo = new THREE.IcosahedronGeometry(0.16, 0);
    geo.scale(1.4, 0.6, 1.1);
    const mat = concreteMaterial(0x8a8071, 0.96);
    mat.name = 'road_grit';
    const items = [];
    for (const p of this.samples) {
      const n = 5;
      for (let i = 0; i < n; i++) {
        const off = rng.sign() * rng.range(5.2, 9.5);
        const q = this._side(p, off);
        const px = q.x + rng.gauss(0, 1.4), pz = q.z + rng.gauss(0, 1.4);
        items.push({ x: px, z: pz, y: eco.height(px, pz), s: rng.range(0.5, 1.9), yaw: rng.next() * 6 });
      }
    }
    const mesh = new THREE.InstancedMesh(geo, mat, items.length);
    mesh.castShadow = false;
    mesh.receiveShadow = true;
    mesh.frustumCulled = false;
    mesh.name = 'road_gravel';
    mesh.count = 0;
    this.root.add(mesh);
    this.gravel = { mesh, items, range: 150 };
    this._lastCam = new THREE.Vector3(1e9, 0, 1e9);
  }

  // ------------------------------------------------------------ skid marks

  /**
   * Rubber laid down at the roadblock and where the wrecks left the road. The
   * ribbon samples terrain height per vertex so it lies on the camber instead
   * of hovering over it.
   */
  _skidMarks() {
    const eco = this.eco;
    const tex = skidTexture();
    const mat = new THREE.MeshBasicMaterial({
      map: tex, transparent: true, opacity: 0.55, depthWrite: false,
      polygonOffset: true, polygonOffsetFactor: -4, polygonOffsetUnits: -4,
      color: 0x1c1a18,
    });
    mat.name = 'road_skid';
    const geos = [];
    const segs = 14;
    const starts = [];
    for (let i = 0; i < this.samples.length; i += 1) {
      const p = this.samples[i];
      if (Math.hypot(p.x, p.z) > 420) continue;
      starts.push(p);
    }
    const rng = new Rng(4242);
    for (let k = 0; k < 7; k++) {
      const p = starts[Math.floor(rng.next() * starts.length)];
      if (!p) continue;
      const lat = rng.range(-2.6, 2.6);
      const drift = rng.range(-3.2, 3.2);
      const pos = [], uv = [], idx = [];
      const len = rng.range(14, 26);
      for (let s = 0; s <= segs; s++) {
        const t = s / segs;
        const along = t * len;
        const lateral = lat + drift * t * t;
        const cx = p.x + p.tx * along + p.tz * lateral;
        const cz = p.z + p.tz * along - p.tx * lateral;
        for (const w of [-1, 1]) {
          const px = cx + p.tz * w * 0.95, pz = cz - p.tx * w * 0.95;
          pos.push(px, eco.height(px, pz) + 0.045, pz);
          uv.push(w * 0.5 + 0.5, t * 1.0);
        }
        if (s > 0) {
          const a = (s - 1) * 2;
          idx.push(a, a + 2, a + 1, a + 1, a + 2, a + 3);
        }
      }
      const g = new THREE.BufferGeometry();
      g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
      g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
      g.setIndex(idx);
      g.computeVertexNormals();
      geos.push(g);
    }
    const B = new PartBuilder();
    for (const g of geos) B.add(mat, g);
    const holder = new THREE.Group();
    B.build(holder, { cast: false, receive: false, name: 'skid' });
    for (const m of holder.children) m.renderOrder = 2;
    this.root.add(holder);
  }

  /**
   * Stream the gravel band in around the camera and gate each road chunk.
   *
   * A marker post is a pixel and a half at three hundred metres; drawing it —
   * and worse, drawing it into three shadow cascades — is pure cost. Chunks
   * fade out past 320 m and stop casting past 110 m.
   */
  update(camPos) {
    for (const c of this.chunkGroups || []) {
      const d = c.center.distanceTo(camPos);
      const vis = d < 340;
      if (c.group.visible !== vis) c.group.visible = vis;
      const cast = c.canCast && d < 110;
      if (c.cast !== cast) {
        c.cast = cast;
        for (const m of c.group.children) m.castShadow = cast;
      }
    }
    const g = this.gravel;
    if (!g) return;
    if (this._lastCam.distanceToSquared(camPos) < 100) return;
    this._lastCam.copy(camPos);
    let w = 0;
    const r2 = g.range * g.range;
    for (const it of g.items) {
      const dx = it.x - camPos.x, dz = it.z - camPos.z;
      if (dx * dx + dz * dz > r2) continue;
      _e.set(0, it.yaw, 0);
      _q.setFromEuler(_e);
      _m.compose(new THREE.Vector3(it.x, it.y - 0.04, it.z), _q,
        new THREE.Vector3(it.s, it.s * 0.8, it.s));
      _m.toArray(g.mesh.instanceMatrix.array, w * 16);
      w++;
      if (w >= g.items.length) break;
    }
    g.mesh.count = w;
    g.mesh.instanceMatrix.needsUpdate = true;
  }
}
